# Generated by Django 5.1.3 on 2024-11-07 16:38

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('pdf', models.FileField(upload_to='books/files/')),
                ('img', stdimage.models.StdImageField(force_min_size=False, upload_to='books/images/', variations={})),
            ],
        ),
    ]
